name: Skip CI

on:
  push:
    branches:
      - main

jobs:
  jobA:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip]') }}
    steps:
      - run: 'echo jobA'
  jobB:
    needs: jobA
    runs-on: ubuntu-latest  
    steps:
      - run: 'echo jobB'
